# Borrowed from here ( https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html ).

sudo: required

language: c++

env:
  - ARCH=x64
  - ARCH=arm

script:
  - "bash -ex .travis_scripts/test_qemu.sh"
